/**
 * Generated by pabble-mpi v1.2.1
 * Date: Mon Oct 27 12:02:07 2014
 */
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <mpi.h>
#include <scribble/pabble.h>

/*** MPI tags ***/
#define Init 0
#define Butterfly 1
#define Finish 2
#define Worker_RANK(x) (0+((x)-(0)))

extern meta_t meta;


int main(int argc, char *argv[])
{
  double ts_overall=0.0, ts_protocol=0.0;
  MPI_Init(&argc, &argv);
  ts_overall = MPI_Wtime();
  meta.comm = MPI_COMM_WORLD;
  MPI_Comm_rank(MPI_COMM_WORLD, &meta.pid);
  MPI_Comm_size(MPI_COMM_WORLD, &meta.nprocs);
  MPI_Group world_grp;
  MPI_Comm_group(MPI_COMM_WORLD, &world_grp);
  /** Declarations (Protocol FFT) **/
  MPI_Barrier(MPI_COMM_WORLD); /* Protocol begin */
#pragma pabble type Complex
  typedef void Complex;
  MPI_Datatype MPI_Complex = MPI_BYTE;
  Complex *bufButterfly0_r;
  MPI_Request req0_r; MPI_Status stat0_r;
  Complex *bufButterfly0_s;
  MPI_Request req0_s; MPI_Status stat0_s;
  ts_protocol=MPI_Wtime();
#pragma pabble Init
  for (int r = 0; r <= 5; r++) {
   for (int i = 0; i <= 63; i++) {
    if ( meta.pid == Worker_RANK(((i+(1<<r))-((1<<(r+1))*((i/(1<<r))%2)))) ) {
     bufButterfly0_r = calloc(meta.buflen(Butterfly), sizeof(Complex));
     MPI_Irecv(bufButterfly0_r, meta.buflen(Butterfly), MPI_Complex, /*Worker[i]*/Worker_RANK(i), Butterfly, meta.comm, &req0_r);
     MPI_Wait(&req0_r, &stat0_r);
     pabble_recvq_enqueue(Butterfly, bufButterfly0_r);
#pragma pabble Butterfly
    }
    if ( meta.pid == Worker_RANK(i) ) {
#pragma pabble Butterfly
     bufButterfly0_s = pabble_sendq_dequeue();
     MPI_Isend(bufButterfly0_s, meta.buflen(Butterfly), MPI_Complex, /*Worker[((i+(1<<r))-((1<<(r+1))*((i/(1<<r))%2)))]*/Worker_RANK(((i+(1<<r))-((1<<(r+1))*((i/(1<<r))%2)))), Butterfly, meta.comm, &req0_s);
     MPI_Wait(&req0_s, &stat0_s);
     free(bufButterfly0_s);
    }
   }
  }
#pragma pabble Finish
  MPI_Barrier(MPI_COMM_WORLD); /* Protocol end */
  ts_protocol=MPI_Wtime()-ts_protocol;
  ts_overall=MPI_Wtime()-ts_overall;
  MPI_Finalize();
  if (meta.pid==0) fprintf(stderr, "Protocol=%fs Overall=%f\n", ts_protocol, ts_overall);
  return EXIT_SUCCESS;
}
